import { db } from "@workspace/db";
import { leads, analyses, searchConfigs } from "@workspace/db";
import { eq, and } from "drizzle-orm";
import { logger } from "../lib/logger.js";
import { decryptSecret } from "../lib/secret-crypto.js";

export async function runTavilyEnrichment(
  leadId: string,
  businessName: string,
  city: string
): Promise<void> {
  try {
    const [config] = await db.select().from(searchConfigs).where(eq(searchConfigs.id, "default"));
    const apiKey = decryptSecret(config?.apiKey) || process.env.TAVILY_API_KEY;
    if (!apiKey) return;

    const query = `${businessName} ${city} Netherlands`;
    const response = await fetch("https://api.tavily.com/search", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        api_key: apiKey,
        query,
        search_depth: "advanced",
        include_answer: true,
        max_results: 5,
      }),
    });

    if (!response.ok) {
      logger.error({ leadId, status: response.status }, "Tavily enrichment failed");
      return;
    }

    const data: any = await response.json();

    const websites = data.results
      .map((r: any) => r.url)
      .filter((url: string) => !url.includes("linkedin.com") && !url.includes("facebook.com"));
    const primaryWebsite = websites.length > 0 ? websites[0] : null;

    await db.insert(analyses).values({
      leadId,
      type: "tavily_enrichment",
      findings: {
        summary: data.answer || "No answer generated by Tavily.",
        results: data.results,
        query: data.query,
      },
    });

    const updates: Record<string, any> = { isTavilyEnriched: true, updatedAt: new Date() };
    if (primaryWebsite) {
      const [existingLead] = await db
        .select({ website: leads.website })
        .from(leads)
        .where(eq(leads.id, leadId));
      if (!existingLead.website) {
        updates.website = primaryWebsite;
        updates.hasWebsite = true;
      }
    }

    await db.update(leads).set(updates).where(eq(leads.id, leadId));
  } catch (error) {
    logger.error({ err: error, leadId }, "Tavily enrichment error");
  }
}
