import { db } from "@workspace/db";
import { leads, analyses, searchConfigs } from "@workspace/db";
import { eq, isNull } from "drizzle-orm";
import { logger } from "../lib/logger.js";
import { decryptSecret } from "../lib/secret-crypto.js";

/**
 * HIGH-2 fix: resolve Tavily key using proper workspace-scoped lookup.
 *
 * Priority order:
 *  1. Workspace-specific searchConfig (workspaceId = provided ID)
 *  2. Global searchConfig (workspaceId IS NULL)
 *  3. TAVILY_API_KEY env var
 *
 * Previously used: `WHERE id = 'default'` — broken after migration 8
 * (workspace multitenancy). That row never exists, so enrichment silently
 * skipped Tavily and fell back only to the env var.
 */
async function resolveTavilyKey(workspaceId?: string | null): Promise<string | null> {
  try {
    // 1. Workspace-specific config
    if (workspaceId) {
      const [wsCfg] = await db
        .select({ apiKey: searchConfigs.apiKey })
        .from(searchConfigs)
        .where(eq(searchConfigs.workspaceId, workspaceId))
        .limit(1);
      const key = decryptSecret(wsCfg?.apiKey);
      if (key) return key;
    }

    // 2. Global / owner-level config (workspaceId IS NULL)
    const [globalCfg] = await db
      .select({ apiKey: searchConfigs.apiKey })
      .from(searchConfigs)
      .where(isNull(searchConfigs.workspaceId))
      .limit(1);
    const globalKey = decryptSecret(globalCfg?.apiKey);
    if (globalKey) return globalKey;
  } catch (err) {
    logger.warn({ err }, "enrichment: failed to read searchConfigs from DB — falling back to env var");
  }

  // 3. Environment variable fallback
  return process.env.TAVILY_API_KEY ?? null;
}

export async function runTavilyEnrichment(
  leadId: string,
  businessName: string,
  city: string,
  workspaceId?: string | null
): Promise<void> {
  try {
    const apiKey = await resolveTavilyKey(workspaceId);
    if (!apiKey) return;

    const query = `${businessName} ${city} Netherlands`;
    const response = await fetch("https://api.tavily.com/search", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        api_key: apiKey,
        query,
        search_depth: "advanced",
        include_answer: true,
        max_results: 5,
      }),
    });

    if (!response.ok) {
      logger.error({ leadId, status: response.status }, "Tavily enrichment failed");
      return;
    }

    const data: any = await response.json();

    const websites = data.results
      .map((r: any) => r.url)
      .filter((url: string) => !url.includes("linkedin.com") && !url.includes("facebook.com"));
    const primaryWebsite = websites.length > 0 ? websites[0] : null;

    await db.insert(analyses).values({
      leadId,
      type: "tavily_enrichment",
      findings: {
        summary: data.answer || "No answer generated by Tavily.",
        results: data.results,
        query: data.query,
      },
    });

    const updates: Record<string, any> = { isTavilyEnriched: true, updatedAt: new Date() };
    if (primaryWebsite) {
      const [existingLead] = await db
        .select({ website: leads.website })
        .from(leads)
        .where(eq(leads.id, leadId));
      if (!existingLead.website) {
        updates.website = primaryWebsite;
        updates.hasWebsite = true;
      }
    }

    await db.update(leads).set(updates).where(eq(leads.id, leadId));
  } catch (error) {
    logger.error({ err: error, leadId }, "Tavily enrichment error");
  }
}
