import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

vi.mock('bullmq', () => {
  const MockQueue = vi.fn().mockImplementation((name: string, opts: any) => ({
    name,
    connection: opts.connection,
  }));
  const MockWorker = vi.fn().mockImplementation((name: string, processor: any, opts: any) => ({
    name,
    processor,
    connection: opts.connection,
  }));
  return { Queue: MockQueue, Worker: MockWorker };
});

import { Queue, Worker } from 'bullmq';

describe('createRedisConnection', () => {
  beforeEach(() => {
    vi.unstubAllEnvs();
    vi.resetModules();
  });

  async function importWithRedisUrl(url: string | undefined) {
    if (url !== undefined) {
      vi.stubEnv('REDIS_URL', url);
    }
    const mod = await import('./index');
    return mod.createRedisConnection();
  }

  it('should parse a full Redis URL with all components', async () => {
    const connection = await importWithRedisUrl('redis://user:secretpassword@redis.example.com:6380');
    expect(connection).toEqual({
      host: 'redis.example.com',
      port: 6380,
      password: 'secretpassword',
    });
  });

  it('should default to localhost:6379 when REDIS_URL is not set', async () => {
    const connection = await importWithRedisUrl(undefined);
    expect(connection).toEqual({
      host: 'localhost',
      port: 6379,
      password: undefined,
    });
  });

  it('should default to port 6379 if the URL has no explicit port', async () => {
    const connection = await importWithRedisUrl('redis://localhost');
    expect(connection.port).toBe(6379);
  });

  it('should throw for an invalid URL with a non-numeric port', async () => {
    await expect(importWithRedisUrl('redis://localhost:abc')).rejects.toThrow();
  });

  it('should return undefined for password if none is provided in the URL', async () => {
    const connection = await importWithRedisUrl('redis://localhost:6379');
    expect(connection.password).toBeUndefined();
  });

  it('should handle empty string password correctly by returning undefined', async () => {
    const connection = await importWithRedisUrl('redis://:@localhost:6379');
    expect(connection.password).toBeUndefined();
  });

  it('should use the REDIS_URL environment variable over the default', async () => {
    const connection = await importWithRedisUrl('redis://custom-host:9999');
    expect(connection.host).toBe('custom-host');
    expect(connection.port).toBe(9999);
  });

  it('should parse standard redis:// protocol correctly', async () => {
    const connection = await importWithRedisUrl('redis://127.0.0.1:6379');
    expect(connection.host).toBe('127.0.0.1');
  });

  it('should parse rediss:// (TLS) protocol correctly without crashing', async () => {
    const connection = await importWithRedisUrl('rediss://secure.redis.com:6380');
    expect(connection.host).toBe('secure.redis.com');
    expect(connection.port).toBe(6380);
  });
});

describe('createQueue', () => {
  it('should instantiate a BullMQ Queue with the provided name and connection details', async () => {
    vi.resetModules();
    vi.unstubAllEnvs();
    const { createQueue } = await import('./index');

    const queue = createQueue('test-queue');

    expect(Queue).toHaveBeenCalledWith('test-queue', expect.objectContaining({
      connection: expect.any(Object),
    }));
    expect(queue.name).toBe('test-queue');
  });

  it('should propagate the connection object generated by createRedisConnection', async () => {
    vi.resetModules();
    vi.unstubAllEnvs();
    const { createQueue } = await import('./index');

    const queue = createQueue('conn-test');

    expect(queue.connection).toEqual({
      host: 'localhost',
      port: 6379,
      password: undefined,
    });
  });

  it('should allow creating multiple queues with different names', async () => {
    vi.resetModules();
    vi.unstubAllEnvs();
    const { createQueue } = await import('./index');

    const callsBefore = vi.mocked(Queue).mock.calls.length;
    const queue1 = createQueue('queue-one');
    const queue2 = createQueue('queue-two');

    expect(Queue).toHaveBeenCalledTimes(callsBefore + 2);
    expect(queue1.name).toBe('queue-one');
    expect(queue2.name).toBe('queue-two');
  });
});

describe('createWorker', () => {
  it('should instantiate a BullMQ Worker with the provided name, processor, and connection', async () => {
    vi.resetModules();
    vi.unstubAllEnvs();
    const { createWorker } = await import('./index');

    const mockProcessor = vi.fn();
    const worker = createWorker('test-worker', mockProcessor);

    expect(Worker).toHaveBeenCalledWith('test-worker', mockProcessor, expect.objectContaining({
      connection: expect.any(Object),
    }));
    expect(worker.name).toBe('test-worker');
    expect(worker.processor).toBe(mockProcessor);
  });

  it('should correctly pass a typed processor function that matches BullMQ job signature', async () => {
    vi.resetModules();
    vi.unstubAllEnvs();
    const { createWorker } = await import('./index');

    const mockProcessor = vi.fn().mockResolvedValue('mock-result');
    const worker = createWorker<{ id: string }, string>('typed-worker', mockProcessor);

    // Simulate BullMQ calling the processor
    const mockJob = { id: 'job-123', data: { id: 'data-123' } };
    const result = await worker.processor(mockJob);

    expect(mockProcessor).toHaveBeenCalledWith(mockJob);
    expect(result).toBe('mock-result');
  });

  it('should propagate connection settings to the worker', async () => {
    vi.resetModules();
    vi.unstubAllEnvs();
    const { createWorker } = await import('./index');

    const worker = createWorker('conn-worker', vi.fn());

    expect(worker.connection).toEqual({
      host: 'localhost',
      port: 6379,
      password: undefined,
    });
  });

  it('should maintain the exact job shape passed to the processor (id and data)', async () => {
    vi.resetModules();
    vi.unstubAllEnvs();
    const { createWorker } = await import('./index');

    const receivedJobs: any[] = [];
    const trackingProcessor = async (job: any) => {
      receivedJobs.push(job);
      return 'tracked';
    };

    const worker = createWorker('shape-worker', trackingProcessor);

    const mockJob = { id: 'job-id', data: { payload: 'test' } };
    await worker.processor(mockJob);

    expect(receivedJobs.length).toBe(1);
    expect(receivedJobs[0]).toEqual(mockJob);
  });

  it('should handle processor functions that throw errors without crashing the worker creation', async () => {
    vi.resetModules();
    vi.unstubAllEnvs();
    const { createWorker } = await import('./index');

    const errorProcessor = async () => { throw new Error('Processing failed'); };
    expect(() => createWorker('error-worker', errorProcessor)).not.toThrow();
  });
});
