/**
 * PDF report generation for website analysis results.
 *
 * Produces branded FindX analysis reports with scores, findings,
 * and recommended actions suitable for sharing with prospects.
 */

import PDFDocument from "pdfkit";
import type { AnalysisResult, Finding, AutomationOpportunity } from "./types.js";
import { scoreLabel } from "./audits/scoring.js";

const BRAND_COLOR = "#2563EB"; // FindX blue
const CRITICAL_COLOR = "#DC2626";
const WARNING_COLOR = "#F59E0B";
const INFO_COLOR = "#3B82F6";

export function generatePdfReport(
  result: AnalysisResult,
  businessName?: string,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 60, bottom: 60, left: 50, right: 50 },
    });

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // --- Header ---
    doc.fontSize(24).fillColor(BRAND_COLOR).text("FindX", { align: "left" });
    doc
      .fontSize(12)
      .fillColor("#64748B")
      .text("Website Analysis Report", { align: "left" });
    doc.moveDown(0.3);

    if (businessName) {
      doc.fontSize(14).fillColor("#1E293B").text(businessName);
    }
    doc
      .fontSize(10)
      .fillColor("#64748B")
      .text(`URL: ${result.url}`)
      .text(`Date: ${new Date(result.analyzedAt).toLocaleDateString("nl-NL")}`);
    doc.moveDown(1);

    // --- Divider ---
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#E2E8F0").lineWidth(1).stroke();
    doc.moveDown(0.8);

    // --- Overall Score ---
    doc.fontSize(16).fillColor("#1E293B").text("Overall Score", { underline: false });
    doc.moveDown(0.3);

    const label = scoreLabel(result.overallScore);
    doc.fontSize(36).fillColor(scoreColor(result.overallScore)).text(`${result.overallScore}/100`, {
      continued: false,
    });
    doc.fontSize(12).fillColor("#64748B").text(label);
    doc.moveDown(1);

    // --- Category Scores ---
    doc.fontSize(14).fillColor("#1E293B").text("Category Breakdown");
    doc.moveDown(0.3);

    for (const cat of result.categories) {
      const catLabel =
        cat.name.charAt(0).toUpperCase() + cat.name.slice(1);
      doc
        .fontSize(11)
        .fillColor("#334155")
        .text(`${catLabel}: `, { continued: true })
        .fillColor(scoreColor(cat.score))
        .text(`${cat.score}/100`);
    }
    doc.moveDown(1);

    // --- Findings ---
    if (result.findings.length > 0) {
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#E2E8F0").lineWidth(1).stroke();
      doc.moveDown(0.5);
      doc.fontSize(14).fillColor("#1E293B").text("Key Findings");
      doc.moveDown(0.3);

      for (const finding of result.findings.slice(0, 15)) {
        const bullet = severityBullet(finding.severity);
        doc
          .fontSize(10)
          .fillColor(severityColor(finding.severity))
          .text(`${bullet} `, { continued: true })
          .fillColor("#334155")
          .text(
            `${finding.title}${finding.value ? ` (${finding.value})` : ""}`,
          );
      }
      doc.moveDown(1);
    }

    // --- Opportunities ---
    if (result.opportunities.length > 0) {
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#E2E8F0").lineWidth(1).stroke();
      doc.moveDown(0.5);
      doc.fontSize(14).fillColor("#1E293B").text("Recommended Improvements");
      doc.moveDown(0.3);

      for (const opp of result.opportunities.slice(0, 8)) {
        doc
          .fontSize(10)
          .fillColor(BRAND_COLOR)
          .text(`▸ ${opp.title}`, { continued: false });
        doc
          .fontSize(9)
          .fillColor("#64748B")
          .text(`  ${opp.description}`);
        doc
          .fontSize(9)
          .fillColor("#94A3B8")
          .text(`  Impact: ${opp.impact} | Effort: ${opp.effort}`);
        doc.moveDown(0.3);
      }
      doc.moveDown(0.5);
    }

    // --- Footer ---
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#E2E8F0").lineWidth(1).stroke();
    doc.moveDown(0.5);
    doc
      .fontSize(9)
      .fillColor("#94A3B8")
      .text("Generated by FindX — findx.nl", { align: "center" });

    doc.end();
  });
}

function scoreColor(score: number): string {
  if (score >= 90) return "#16A34A";
  if (score >= 70) return "#2563EB";
  if (score >= 50) return "#F59E0B";
  if (score >= 30) return "#EA580C";
  return "#DC2626";
}

function severityColor(severity: string): string {
  if (severity === "critical") return CRITICAL_COLOR;
  if (severity === "warning") return WARNING_COLOR;
  return INFO_COLOR;
}

function severityBullet(severity: string): string {
  if (severity === "critical") return "●";
  if (severity === "warning") return "◐";
  return "○";
}
